### ISSUE TITLE
language support ua

### ISSUE THREAD

**Issue by ikakey** [udacity/ML_SageMaker_Studies#12]
Hi, is the Ukrainian language supported ?
if not, is it possible train model for UA lang?

tnx

**Comment by iboldurev** [comment]
😂😂😂

**Comment by iboldurev** [comment]
On your question, you can add any language to ml, since it's just dummy data (for study)

**Comment by ronny-udacity** [comment]
ML is agnostic to the language since the corpus will be indexed to integers before they're trained. In Natural Language Processing, this step is called `tokenization`. You can read more about tokenization on this [blog post](https://www.analyticsvidhya.com/blog/2020/05/what-is-tokenization-nlp/).
