### ISSUE TITLE
With "sagemaker 2.31.1", "sagemaker.pytorch.PyTorch" needs to specify both "framework_version" and "py_version"

### ISSUE THREAD

**Issue by nov05** [udacity/ML_SageMaker_Studies#15]
In **Moon_Classification_Solution.ipynb**, the original code below would cause an error `ValueError: framework_version or py_version was None, yet image_uri was also None. Either specify both framework_version and py_version, or specify image_uri.` So I specified `py_version='py3'`, cause the framework version only supports `py2` and `py3`, which fixed the problem. Or I guess just add `!pip install sagemaker==1.72.0` like notebooks in another [**repo**](https://github.com/udacity/sagemaker-deployment/blob/master/Mini-Projects/IMDB%20Sentiment%20Analysis%20-%20XGBoost%20(Batch%20Transform)%20-%20Solution.ipynb) would also solve the issue.

```
# import a PyTorch wrapper
from sagemaker.pytorch import PyTorch

# specify an output path
# prefix is specified above
output_path = 's3://{}/{}'.format(bucket, prefix)

# instantiate a pytorch estimator
estimator = PyTorch(entry_point='train.py',
                    source_dir='source_solution', # this should be just "source" for your code
                    role=role,
                    framework_version='1.0',
                    py_version='py3', ### <------------------------ added a line here
                    train_instance_count=1,
                    train_instance_type='ml.c4.xlarge',
                    output_path=output_path,
                    sagemaker_session=sagemaker_session,
                    hyperparameters={
                        'input_dim': 2,  # num of features
                        'hidden_dim': 20,
                        'output_dim': 1,
                        'epochs': 80 # could change to higher
                    })
```

**Comment by abhiojha8** [comment]
Resolved by fixing Sagemaker's version to 1.72.0.
