### ISSUE TITLE
as_matrix deprecated in pandas, throwing error

### ISSUE THREAD

**Issue by markplotlib** [udacity/ML_SageMaker_Studies#16]
Hi,

Sorry, but `pandas.DataFrame.as_matrix()` appears to be deprecated. Can [this notebook ](https://github.com/udacity/ML_SageMaker_Studies/blob/master/Payment_Fraud_Detection/Fraud_Detection_Solution.ipynb) please be updated as a result?

```
def train_test_split(transaction_df, train_frac= 0.7, seed=1):

...

    # convert the df into a matrix for ease of splitting
    df_matrix = transaction_df.as_matrix()
...
```

Thank you!

**Comment by abhiojha8** [comment]
We have fixed this now. Thanks!
