### ISSUE TITLE
1_Data_Exploration: UsageError: Line magic function `%` not found.

### ISSUE THREAD

**Issue by maxi-marufo** [udacity/ML_SageMaker_Studies#2]
There is a small bug in the **1_Data_Exploration** notebook. The line:
`% matplotlib inline`
should be:
`%matplotlib inline`
I open this Issue and not a PR because of git problems tracking ipynb files.

**Comment by IzitoI** [comment]
The error should be fixed now :)

**Comment by bhadreshpsavani** [comment]
No @IzitoI,
Your PR is not merged yet

**Comment by ronny-udacity** [comment]
Thanks for reporting the issue and sending the [PR](https://github.com/udacity/ML_SageMaker_Studies/pull/6). It's been merged now.
