### ISSUE TITLE
make_time_series should use pd.date_range

### ISSUE THREAD

**Issue by tonyjward** [udacity/ML_SageMaker_Studies#3]
In the time series forecasting project
https://github.com/udacity/ML_SageMaker_Studies/blob/master/Time_Series_Forecasting/Energy_Consumption_Exercise.ipynb

we have a function make_time_series that fails here 
`index = pd.DatetimeIndex(start=t_start, end=t_end, freq=freq)`

Instead this should be 
`index = pd.date_range(start=t_start, end = t_end, freq= freq)`

I'm using pandas version 1.0.3

Thanks

Tony

**Comment by brunokiyoshi** [comment]
That is right! came here to find if someone had solved the issue and @tonyjward 's solution works! At first thought it could be a Pandas version issue.

**Comment by bhadreshpsavani** [comment]
Ya I also faced the same issue and this solution worked

**Comment by vlad-ciobaca** [comment]
thanks. this solution worked for me too.

**Comment by ronny-udacity** [comment]
Thank you for reporting the bug. The [PR](https://github.com/udacity/ML_SageMaker_Studies/pull/11) has been merged.
