### ISSUE TITLE
Redundunt Lines in Project_Plagiarism_Detection Notebook 3

### ISSUE THREAD

**Issue by bhadreshpsavani** [udacity/ML_SageMaker_Studies#9]
![image](https://user-images.githubusercontent.com/26653468/96338546-7fd4bd80-10ac-11eb-9d25-0a112dd09286.png)
In project 2 Notebook3 has some redundant line

**Comment by ronny-udacity** [comment]
Thank you for reporting the issue. The [PR](https://github.com/udacity/ML_SageMaker_Studies/pull/13) to fix the issue has been merged.
